{% set version = "0.10.1" %}

package:
  name: pytest-check-links
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/pytest_check_links/pytest_check_links-{{ version }}.tar.gz
  sha256: 7358dd92c8e6c737c8749ec87f5a27c32390445d43182673f89247a1a34d776d

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytest-check-links = pytest_check_links.__main__:main

requirements:
  host:
    - hatchling >=1.5
    - pip
    - python {{ python_min }}
  run:
    - docutils >=0.20.1
    - html5lib >=1.1
    - nbconvert >=7.1
    - nbformat >=5.1
    - pytest >=7.0,<9
    - python >={{ python_min }}
    - requests >=2.22

test:
  imports:
    - pytest_check_links
  commands:
    - pip check
    - pytest-check-links --version
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jupyterlab/pytest-check-links
  summary: pytest plugin that checks URLs for HTML-containing files.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - blink1073
    - bollwyvl
